export const ayuDarkTheme = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '5a6673', fontStyle: 'italic' },
    { token: 'string', foreground: 'aad94c' },
    { token: 'constant.other.symbol', foreground: 'aad94c' },
    { token: 'string.regexp', foreground: '95e6cb' },
    { token: 'constant.character', foreground: '95e6cb' },
    { token: 'constant.other', foreground: '95e6cb' },
    { token: 'constant.numeric', foreground: 'd2a6ff' },
    { token: 'constant.language', foreground: 'd2a6ff' },
    { token: 'variable', foreground: 'bfbdb6' },
    { token: 'variable.parameter.function-call', foreground: 'bfbdb6' },
    { token: 'variable.member', foreground: 'f07178' },
    { token: 'variable.language', foreground: '39bae6', fontStyle: 'italic' },
    { token: 'storage', foreground: 'ff8f40' },
    { token: 'keyword', foreground: 'ff8f40' },
    { token: 'keyword.operator', foreground: 'f29668' },
    { token: 'punctuation.separator', foreground: 'bfbdb6' },
    { token: 'punctuation.terminator', foreground: 'bfbdb6' },
    { token: 'punctuation.section', foreground: 'bfbdb6' },
    { token: 'punctuation.accessor', foreground: 'f29668' },
    { token: 'punctuation.definition.template-expression', foreground: 'ff8f40' },
    { token: 'punctuation.section.embedded', foreground: 'ff8f40' },
    { token: 'meta.embedded', foreground: 'bfbdb6' },
    { token: 'source.java storage.type', foreground: '59c2ff' },
    { token: 'source.haskell storage.type', foreground: '59c2ff' },
    { token: 'source.c storage.type', foreground: '59c2ff' },
    { token: 'entity.other.inherited-class', foreground: '39bae6' },
    { token: 'storage.type.function', foreground: 'ff8f40' },
    { token: 'source.java storage.type.primitive', foreground: '39bae6' },
    { token: 'entity.name.function', foreground: 'ffb454' },
    { token: 'variable.parameter', foreground: 'd2a6ff' },
    { token: 'meta.parameter', foreground: 'd2a6ff' },
    { token: 'variable.function', foreground: 'ffb454' },
    { token: 'variable.annotation', foreground: 'ffb454' },
    { token: 'meta.function-call.generic', foreground: 'ffb454' },
    { token: 'support.function.go', foreground: 'ffb454' },
    { token: 'support.function', foreground: 'f07178' },
    { token: 'support.macro', foreground: 'f07178' },
    { token: 'entity.name.import', foreground: 'aad94c' },
    { token: 'entity.name.package', foreground: 'aad94c' },
    { token: 'entity.name', foreground: '59c2ff' },
    { token: 'entity.name.tag', foreground: '39bae6' },
    { token: 'meta.tag.sgml', foreground: '39bae6' },
    { token: 'support.class.component', foreground: '59c2ff' },
    { token: 'punctuation.definition.tag.end', foreground: '39bae6' },
    { token: 'punctuation.definition.tag.begin', foreground: '39bae6' },
    { token: 'punctuation.definition.tag', foreground: '39bae6' },
    { token: 'entity.other.attribute-name', foreground: 'ffb454' },
    { token: 'entity.other.attribute-name.pseudo-class', foreground: '95e6cb' },
    { token: 'support.constant', foreground: 'f29668', fontStyle: 'italic' },
    { token: 'support.type', foreground: '39bae6' },
    { token: 'support.class', foreground: '39bae6' },
    { token: 'source.go storage.type', foreground: '39bae6' },
    { token: 'meta.decorator variable.other', foreground: 'e6c08a' },
    { token: 'meta.decorator punctuation.decorator', foreground: 'e6c08a' },
    { token: 'storage.type.annotation', foreground: 'e6c08a' },
    { token: 'entity.name.function.decorator', foreground: 'e6c08a' },
    { token: 'invalid', foreground: 'd95757' },
    { token: 'meta.diff', foreground: 'c594c5' },
    { token: 'meta.diff.header', foreground: 'c594c5' },
    { token: 'source.ruby variable.other.readwrite', foreground: 'ffb454' },
    { token: 'source.css entity.name.tag', foreground: '59c2ff' },
    { token: 'source.sass entity.name.tag', foreground: '59c2ff' },
    { token: 'source.scss entity.name.tag', foreground: '59c2ff' },
    { token: 'source.less entity.name.tag', foreground: '59c2ff' },
    { token: 'source.stylus entity.name.tag', foreground: '59c2ff' },
    { token: 'source.css support.type', foreground: '5a6673' },
    { token: 'source.sass support.type', foreground: '5a6673' },
    { token: 'source.scss support.type', foreground: '5a6673' },
    { token: 'source.less support.type', foreground: '5a6673' },
    { token: 'source.stylus support.type', foreground: '5a6673' },
    { token: 'support.type.property-name', foreground: '39bae6', fontStyle: 'normal' },
    { token: 'constant.numeric.line-number.find-in-files - match', foreground: '5a6673' },
    { token: 'constant.numeric.line-number.match', foreground: 'ff8f40' },
    { token: 'entity.name.filename.find-in-files', foreground: 'aad94c' },
    { token: 'message.error', foreground: 'd95757' },
    { token: 'markup.heading', foreground: 'aad94c', fontStyle: 'bold' },
    { token: 'markup.heading entity.name', foreground: 'aad94c', fontStyle: 'bold' },
    { token: 'markup.underline.link', foreground: '39bae6' },
    { token: 'string.other.link', foreground: '39bae6' },
    { token: 'markup.italic', foreground: 'f07178', fontStyle: 'italic' },
    { token: 'emphasis', foreground: 'f07178', fontStyle: 'italic' },
    { token: 'markup.bold', foreground: 'f07178', fontStyle: 'bold' },
    { token: 'markup.underline', fontStyle: 'underline' },
    { token: 'markup.italic markup.bold', fontStyle: 'bold italic' },
    { token: 'markup.bold markup.italic', fontStyle: 'bold italic' },
    { token: 'markup.raw', background: 'bfbdb6' },
    { token: 'markup.raw.inline', background: 'bfbdb6' },
    { token: 'meta.separator', foreground: '5a6673', background: 'bfbdb6', fontStyle: 'bold' },
    { token: 'markup.quote', foreground: '95e6cb', fontStyle: 'italic' },
    { token: 'markup.list punctuation.definition.list.begin', foreground: 'ffb454' },
    { token: 'markup.inserted', foreground: '70bf56' },
    { token: 'markup.changed', foreground: '73b8ff' },
    { token: 'markup.deleted', foreground: 'f26d78' },
    { token: 'markup.strike', foreground: 'e6c08a' },
    { token: 'markup.strong', fontStyle: 'bold' },
    { token: 'markup.table', foreground: '39bae6', background: 'bfbdb6' },
    { token: 'text.html.markdown markup.inline.raw', foreground: 'f29668' },
    { token: 'text.html.markdown meta.dummy.line-break', foreground: '5a6673', background: '5a6673' },
    { token: 'punctuation.definition.markdown', foreground: '5a6673', background: 'bfbdb6' },
  ],
  colors: {
    'actionBar.toggledBackground': '#475266',
    'activityBar.activeBorder': '#e6b450',
    'activityBar.background': '#0d1017',
    'activityBar.border': '#1b1f29',
    'activityBar.foreground': '#5a6378',
    'activityBar.inactiveForeground': '#5a6378',
    'activityBarBadge.background': '#e6b450',
    'activityBarBadge.foreground': '#765b24',
    'activityBarTop.activeBorder': '#e6b450',
    'activityBarTop.foreground': '#697184',
    'badge.background': '#e6b450',
    'badge.foreground': '#e6b450',
    'button.background': '#e6b450',
    'button.border': '#765b24',
    'button.foreground': '#765b24',
    'button.hoverBackground': '#deae4d',
    'button.secondaryBackground': '#5a6378',
    'button.secondaryForeground': '#bfbdb6',
    'button.secondaryHoverBackground': '#5a6378',
    'button.separator': '#765b24',
    'chat.checkpointSeparator': '#5a6673',
    'chat.editedFileForeground': '#73b8ff',
    'chat.requestBackground': '#0d1017',
    'chat.requestBorder': '#475266',
    'chat.requestBubbleBackground': '#475266',
    'chat.requestBubbleHoverBackground': '#475266',
    'chat.slashCommandBackground': '#39bae6',
    'chat.slashCommandForeground': '#39bae6',
    'commandCenter.activeBackground': '#475266',
    'commandCenter.activeBorder': '#475266',
    'commandCenter.activeForeground': '#5a6378',
    'commandCenter.background': '#10141c',
    'commandCenter.border': '#1b1f29',
    'commandCenter.foreground': '#5a6378',
    'commandCenter.inactiveBorder': '#1b1f29',
    'debugConsoleInputIcon.foreground': '#e6b450',
    'debugExceptionWidget.background': '#141821',
    'debugExceptionWidget.border': '#1b1f29',
    'debugIcon.breakpointDisabledForeground': '#f29668',
    'debugIcon.breakpointForeground': '#f29668',
    'debugToolBar.background': '#141821',
    'descriptionForeground': '#5a6378',
    'diffEditor.diagonalFill': '#1b1f29',
    'diffEditor.insertedTextBackground': '#70bf56',
    'diffEditor.removedTextBackground': '#f26d78',
    'disabledForeground': '#5a6378',
    'dropdown.background': '#141821',
    'dropdown.border': '#1b1f29',
    'dropdown.foreground': '#5a6378',
    'editor.background': '#10141c',
    'editor.findMatchBackground': '#4c4126',
    'editor.findMatchHighlightBackground': '#4c4126',
    'editor.foreground': '#bfbdb6',
    'editor.inactiveSelectionBackground': '#80b5ff',
    'editor.lineHighlightBackground': '#161a24',
    'editor.rangeHighlightBackground': '#4c4126',
    'editor.selectionBackground': '#3388ff',
    'editor.selectionHighlightBackground': '#70bf56',
    'editor.selectionHighlightBorder': '#70bf56',
    'editor.snippetTabstopHighlightBackground': '#70bf56',
    'editor.wordHighlightBackground': '#73b8ff',
    'editor.wordHighlightBorder': '#73b8ff',
    'editor.wordHighlightStrongBackground': '#70bf56',
    'editor.wordHighlightStrongBorder': '#70bf56',
    'editorBracketMatch.background': '#5a6378',
    'editorBracketMatch.border': '#5a6378',
    'editorCodeLens.foreground': '#5a6673',
    'editorCursor.foreground': '#e6b450',
    'editorError.foreground': '#d95757',
    'editorGroup.background': '#141821',
    'editorGroup.border': '#1b1f29',
    'editorGroupHeader.noTabsBackground': '#0d1017',
    'editorGroupHeader.tabsBackground': '#0d1017',
    'editorGroupHeader.tabsBorder': '#1b1f29',
    'editorGutter.addedBackground': '#70bf56',
    'editorGutter.deletedBackground': '#f26d78',
    'editorGutter.modifiedBackground': '#73b8ff',
    'editorHoverWidget.background': '#141821',
    'editorHoverWidget.border': '#1b1f29',
    'editorIndentGuide.activeBackground': '#5a6378',
    'editorIndentGuide.background': '#5a6378',
    'editorInlayHint.foreground': '#bfbdb6',
    'editorLineNumber.activeForeground': '#5a6378',
    'editorLineNumber.foreground': '#5a6378',
    'editorLink.activeForeground': '#e6b450',
    'editorMarkerNavigation.background': '#141821',
    'editorOverviewRuler.addedForeground': '#70bf56',
    'editorOverviewRuler.border': '#1b1f29',
    'editorOverviewRuler.bracketMatchForeground': '#5a6378',
    'editorOverviewRuler.deletedForeground': '#f26d78',
    'editorOverviewRuler.errorForeground': '#d95757',
    'editorOverviewRuler.findMatchForeground': '#4c4126',
    'editorOverviewRuler.modifiedForeground': '#73b8ff',
    'editorOverviewRuler.warningForeground': '#e6b450',
    'editorOverviewRuler.wordHighlightForeground': '#73b8ff',
    'editorOverviewRuler.wordHighlightStrongForeground': '#70bf56',
    'editorRuler.foreground': '#5a6378',
    'editorStickyScroll.border': '#1b1f29',
    'editorStickyScroll.shadow': '#000000',
    'editorStickyScrollHover.background': '#475266',
    'editorSuggestWidget.background': '#141821',
    'editorSuggestWidget.border': '#1b1f29',
    'editorSuggestWidget.highlightForeground': '#e6b450',
    'editorSuggestWidget.selectedBackground': '#475266',
    'editorWarning.foreground': '#e6b450',
    'editorWhitespace.foreground': '#5a6378',
    'editorWidget.background': '#141821',
    'editorWidget.border': '#1b1f29',
    'editorWidget.resizeBorder': '#141821',
    'errorForeground': '#d95757',
    'extensionButton.prominentBackground': '#e6b450',
    'extensionButton.prominentForeground': '#765b24',
    'extensionButton.prominentHoverBackground': '#e2b14f',
    'focusBorder': '#e6b450',
    'foreground': '#5a6378',
    'gitDecoration.conflictingResourceForeground': '',
    'gitDecoration.deletedResourceForeground': '#f26d78',
    'gitDecoration.ignoredResourceForeground': '#5a6378',
    'gitDecoration.modifiedResourceForeground': '#73b8ff',
    'gitDecoration.submoduleResourceForeground': '#d2a6ff',
    'gitDecoration.untrackedResourceForeground': '#70bf56',
    'icon.foreground': '#5a6378',
    'inlineChat.background': '#141821',
    'inlineChat.border': '#1b1f29',
    'inlineChat.foreground': '#bfbdb6',
    'inlineChat.shadow': '#000000',
    'inlineChatDiff.inserted': '#70bf56',
    'inlineChatDiff.removed': '#f26d78',
    'inlineChatInput.background': '#10141c',
    'inlineChatInput.border': '#1b1f29',
    'inlineChatInput.focusBorder': '#e6b450',
    'inlineChatInput.placeholderForeground': '#5a6378',
    'inlineEdit.gutterIndicator.background': '#1b1f29',
    'inlineEdit.gutterIndicator.primaryBackground': '#e6b450',
    'inlineEdit.gutterIndicator.primaryBorder': '#e6b450',
    'inlineEdit.gutterIndicator.primaryForeground': '#e6b450',
    'inlineEdit.gutterIndicator.secondaryBackground': '#5a6378',
    'inlineEdit.gutterIndicator.secondaryBorder': '#5a6378',
    'inlineEdit.gutterIndicator.secondaryForeground': '#5a6378',
    'inlineEdit.gutterIndicator.successfulBackground': '#70bf56',
    'inlineEdit.gutterIndicator.successfulBorder': '#70bf56',
    'inlineEdit.gutterIndicator.successfulForeground': '#70bf56',
    'inlineEdit.modifiedBackground': '#70bf56',
    'inlineEdit.modifiedBorder': '#70bf56',
    'inlineEdit.modifiedChangedLineBackground': '#70bf56',
    'inlineEdit.modifiedChangedTextBackground': '#70bf56',
    'inlineEdit.originalBackground': '#f26d78',
    'inlineEdit.originalBorder': '#f26d78',
    'inlineEdit.originalChangedLineBackground': '#f26d78',
    'inlineEdit.originalChangedTextBackground': '#f26d78',
    'input.background': '#10141c',
    'input.border': '#5a6378',
    'input.foreground': '#bfbdb6',
    'input.placeholderForeground': '#5a6378',
    'inputOption.activeBackground': '#e6b450',
    'inputOption.activeBorder': '#e6b450',
    'inputOption.activeForeground': '#e6b450',
    'inputOption.hoverBackground': '#5a6378',
    'inputValidation.errorBackground': '#10141c',
    'inputValidation.errorBorder': '#d95757',
    'inputValidation.infoBackground': '#0d1017',
    'inputValidation.infoBorder': '#39bae6',
    'inputValidation.warningBackground': '#0d1017',
    'inputValidation.warningBorder': '#ffb454',
    'keybindingLabel.background': '#5a6378',
    'keybindingLabel.border': '#bfbdb6',
    'keybindingLabel.bottomBorder': '#bfbdb6',
    'keybindingLabel.foreground': '#bfbdb6',
    'list.activeSelectionBackground': '#475266',
    'list.activeSelectionForeground': '#bfbdb6',
    'list.deemphasizedForeground': '#d95757',
    'list.errorForeground': '#d95757',
    'list.filterMatchBackground': '#433921',
    'list.filterMatchBorder': '#4c4126',
    'list.focusBackground': '#475266',
    'list.focusForeground': '#bfbdb6',
    'list.focusOutline': '#475266',
    'list.highlightForeground': '#e6b450',
    'list.hoverBackground': '#475266',
    'list.inactiveSelectionBackground': '#475266',
    'list.inactiveSelectionForeground': '#5a6378',
    'list.invalidItemForeground': '#5a6378',
    'listFilterWidget.background': '#141821',
    'listFilterWidget.noMatchesOutline': '#d95757',
    'listFilterWidget.outline': '#e6b450',
    'menu.background': '#0f131a',
    'menu.border': '#1b1f29',
    'menu.foreground': '#5a6378',
    'menu.selectionBackground': '#475266',
    'menu.selectionBorder': '#475266',
    'menu.separatorBackground': '#1b1f29',
    'minimap.background': '#10141c',
    'minimap.errorHighlight': '#d95757',
    'minimap.findMatchHighlight': '#4c4126',
    'minimap.selectionHighlight': '#3388ff',
    'minimapGutter.addedBackground': '#70bf56',
    'minimapGutter.deletedBackground': '#f26d78',
    'minimapGutter.modifiedBackground': '#73b8ff',
    'multiDiffEditor.background': '#0d1017',
    'multiDiffEditor.border': '#1b1f29',
    'multiDiffEditor.headerBackground': '#141821',
    'panel.background': '#0d1017',
    'panel.border': '#1b1f29',
    'panelStickyScroll.border': '#1b1f29',
    'panelStickyScroll.shadow': '#000000',
    'panelTitle.activeBorder': '#e6b450',
    'panelTitle.activeForeground': '#bfbdb6',
    'panelTitle.inactiveForeground': '#5a6378',
    'peekView.border': '#475266',
    'peekViewEditor.background': '#141821',
    'peekViewEditor.matchHighlightBackground': '#4c4126',
    'peekViewEditor.matchHighlightBorder': '#433921',
    'peekViewResult.background': '#141821',
    'peekViewResult.fileForeground': '#bfbdb6',
    'peekViewResult.lineForeground': '#5a6378',
    'peekViewResult.matchHighlightBackground': '#4c4126',
    'peekViewResult.selectionBackground': '#475266',
    'peekViewTitle.background': '#475266',
    'peekViewTitleDescription.foreground': '#5a6378',
    'peekViewTitleLabel.foreground': '#bfbdb6',
    'pickerGroup.border': '#1b1f29',
    'pickerGroup.foreground': '#5a6378',
    'profileBadge.background': '#e6b450',
    'profileBadge.foreground': '#765b24',
    'progressBar.background': '#e6b450',
    'scrollbar.shadow': '#1b1f29',
    'scrollbarSlider.activeBackground': '#5a6378',
    'scrollbarSlider.background': '#5a6378',
    'scrollbarSlider.hoverBackground': '#5a6378',
    'selection.background': '#3388ff',
    'settings.headerForeground': '#bfbdb6',
    'settings.modifiedItemIndicator': '#73b8ff',
    'sideBar.background': '#0d1017',
    'sideBar.border': '#1b1f29',
    'sideBarSectionHeader.background': '#0d1017',
    'sideBarSectionHeader.border': '#1b1f29',
    'sideBarSectionHeader.foreground': '#5a6378',
    'sideBarStickyScroll.border': '#1b1f29',
    'sideBarStickyScroll.shadow': '#000000',
    'sideBarTitle.foreground': '#5a6378',
    'statusBar.background': '#0d1017',
    'statusBar.border': '#1b1f29',
    'statusBar.debuggingBackground': '#f29668',
    'statusBar.debuggingForeground': '#10141c',
    'statusBar.foreground': '#5a6378',
    'statusBar.noFolderBackground': '#141821',
    'statusBarItem.activeBackground': '#5a6378',
    'statusBarItem.hoverBackground': '#5a6378',
    'statusBarItem.prominentBackground': '#1b1f29',
    'statusBarItem.prominentHoverBackground': '#000000',
    'statusBarItem.remoteBackground': '#e6b450',
    'statusBarItem.remoteForeground': '#765b24',
    'symbolIcon.arrayForeground': '#59c2ff',
    'symbolIcon.booleanForeground': '#d2a6ff',
    'symbolIcon.classForeground': '#59c2ff',
    'symbolIcon.colorForeground': '#e6c08a',
    'symbolIcon.constantForeground': '#d2a6ff',
    'symbolIcon.constructorForeground': '#ffb454',
    'symbolIcon.enumeratorForeground': '#59c2ff',
    'symbolIcon.enumeratorMemberForeground': '#d2a6ff',
    'symbolIcon.eventForeground': '#e6c08a',
    'symbolIcon.fieldForeground': '#f07178',
    'symbolIcon.fileForeground': '#5a6378',
    'symbolIcon.folderForeground': '#5a6378',
    'symbolIcon.functionForeground': '#ffb454',
    'symbolIcon.interfaceForeground': '#59c2ff',
    'symbolIcon.keyForeground': '#39bae6',
    'symbolIcon.keywordForeground': '#ff8f40',
    'symbolIcon.methodForeground': '#ffb454',
    'symbolIcon.moduleForeground': '#aad94c',
    'symbolIcon.namespaceForeground': '#aad94c',
    'symbolIcon.nullForeground': '#d2a6ff',
    'symbolIcon.numberForeground': '#d2a6ff',
    'symbolIcon.objectForeground': '#59c2ff',
    'symbolIcon.operatorForeground': '#f29668',
    'symbolIcon.packageForeground': '#aad94c',
    'symbolIcon.propertyForeground': '#f07178',
    'symbolIcon.referenceForeground': '#59c2ff',
    'symbolIcon.snippetForeground': '#e6c08a',
    'symbolIcon.stringForeground': '#aad94c',
    'symbolIcon.structForeground': '#59c2ff',
    'symbolIcon.textForeground': '#bfbdb6',
    'symbolIcon.typeParameterForeground': '#59c2ff',
    'symbolIcon.unitForeground': '#d2a6ff',
    'symbolIcon.variableForeground': '#bfbdb6',
    'tab.activeBackground': '#10141c',
    'tab.activeBorder': '#10141c',
    'tab.activeBorderTop': '#e6b450',
    'tab.activeForeground': '#bfbdb6',
    'tab.border': '#1b1f29',
    'tab.inactiveBackground': '#0d1017',
    'tab.inactiveForeground': '#5a6378',
    'tab.unfocusedActiveBorderTop': '#5a6378',
    'tab.unfocusedActiveForeground': '#5a6378',
    'tab.unfocusedInactiveForeground': '#5a6378',
    'terminal.ansiBlack': '#1b1f29',
    'terminal.ansiBlue': '#4fbfff',
    'terminal.ansiBrightBlack': '#686868',
    'terminal.ansiBrightBlue': '#59c2ff',
    'terminal.ansiBrightCyan': '#95e6cb',
    'terminal.ansiBrightGreen': '#aad94c',
    'terminal.ansiBrightMagenta': '#d2a6ff',
    'terminal.ansiBrightRed': '#f07178',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightYellow': '#ffb454',
    'terminal.ansiCyan': '#93e2c8',
    'terminal.ansiGreen': '#70bf56',
    'terminal.ansiMagenta': '#d0a1ff',
    'terminal.ansiRed': '#f06b73',
    'terminal.ansiWhite': '#c7c7c7',
    'terminal.ansiYellow': '#fdb04c',
    'terminal.background': '#0d1017',
    'terminal.foreground': '#bfbdb6',
    'terminalCommandGuide.foreground': '#5a6378',
    'terminalStickyScroll.border': '#1b1f29',
    'terminalStickyScroll.shadow': '#000000',
    'terminalStickyScrollHover.background': '#475266',
    'textBlockQuote.background': '#141821',
    'textLink.activeForeground': '#e6b450',
    'textLink.foreground': '#e6b450',
    'textPreformat.foreground': '#bfbdb6',
    'titleBar.activeBackground': '#0d1017',
    'titleBar.activeForeground': '#5a6378',
    'titleBar.border': '#1b1f29',
    'titleBar.inactiveBackground': '#0d1017',
    'titleBar.inactiveForeground': '#5a6378',
    'toolbar.hoverBackground': '#475266',
    'tree.indentGuidesStroke': '#5a6378',
    'walkThrough.embeddedEditorBackground': '#141821',
    'welcomePage.buttonBackground': '#e6b450',
    'welcomePage.progress.background': '#161a24',
    'welcomePage.tileBackground': '#0d1017',
    'welcomePage.tileShadow': '#000000',
    'widget.border': '#1b1f29',
    'widget.shadow': '#000000',
  },
};